services:
  go_app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/app  
     - external-storage:/media/uploads/1
    tty: true
    stdin_open: true

volumes:
  external-storage:
    external: true
